spring.datasource.url=jdbc:mysql://localhost:3306/trading_app_db?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081
api.key=1d08d274417ec1b5a056096ba54f1185
